### ISSUE TITLE
OpenGL2: Add missing DDS texture support from Xreal

### ISSUE THREAD

**Issue by KuehnhammerTobias** [KuehnhammerTobias/ioid3-WIP#4]

**Comment by zturtleman** [comment]
There is DDS support (uncompressed / DXTn) sitting in [ioq3 bugzilla](https://bugzilla.icculus.org/show_bug.cgi?id=5442). I've updated patches 2, 3, and 4 for ioq3 at https://github.com/zturtleman/ioq3/tree/codec/dds if that helps. It's also in Spearmint for Star Trek Elite Force 2.
