### ISSUE TITLE
Make compiling more Windows friendly again

### ISSUE THREAD

**Issue by KuehnhammerTobias** [KuehnhammerTobias/ioid3-WIP#6]
Currently the only way I know to compile the code on Windows is by using Cygwin,  or by using a real outdated version of MinGW + MSYS.
So, bring back better Windows support. http://community.ioquake.org/t/compiling-source-with-vs2013-express/156
Either by fixing MSVC project files: https://github.com/ioquake/ioq3/pull/67
or by using MSYS2 instead: https://github.com/ioquake/ioq3/pull/110

Spearmint (ioid3) has no MSVC support at all :/

**Comment by zturtleman** [comment]
MSYS2 support has been merged into ioq3 and Spearmint.
